<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class NailProductSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Create/Get Unit
        $unit = Unit::firstOrCreate(['name' => 'Pcs'], ['short_name' => 'pcs']);

        // 2. Create/Get Category
        $category = Category::firstOrCreate(
            ['name' => 'Nail'],
            ['prefix' => 'NL']
        );

        // 3. Products List (Raw)
        $rawProducts = [
            'Peony base coat',
            'Peony top coat',
            'Peony bloom',
            'Peony primer',
            'Peony matte',
            'Peony warna',
            'Rising lady hitam',
            'Rising lady silver',
            'Sugar cat eye',
            'Lachomcir base',
            'Lachomcir ph bond',
            'Lachomcir color',
            'LUGX Putih',
            'LUGX Hitam',
            'Roniki color',
            'PH bond',
            'Top shimmer',
            'Top coat roniki',
            'Base coat',
            'Blooming gel',
            'Overlay',
            'Vitamin cutikula',
            'Nail glue BYB',
            'Mx bond',
            'Vitamin biola',
            'Top coat chrome',
            'Gliter AS',
            'Cat eye AS',
            'Cat eye anies',
            'Cat eye gyeoul',
            'Cat eye botol putih',
            'Cat eye kaniu',
            'Cat eye danicol',
            'Cat eye cepuk',
            'Cat eye cepuk pink',
            'Liner gold',
            'Liner putih',
            'Liner silver',
            'Mydance gel',
            'Gyeoul color',
            'Sugar color',
            'annies color',
            'Kupal rising lady S',
            'Soft gel panjang box',
            'Half tip square box',
            'Soft tip menail set 20 pcs',
            'Scrub cuccio',
            'Masker cuccio',
            'Collagen tangan',
            'Refill foot file',
            'Spray callus',
            'Scrub callus',
            'Lotion callus',
            'Foot soak',
            'Mousse footlogix',
            'Jepit aksesoris',
            'Acc shell box',
            'Ombre powder',
            'Acc bunga campur box',
            'Acc shell pastel box',
            'Acc jewel campur box',
            'Acc foil campur box',
            'Powder chrome',
            'Chrome gold',
            'Chrome silver',
            'Glitter bubuk',
            'Silver foil',
            'Caviar silver',
            'Nail foil aurora',
            'Acc pita gold besar',
            'Permata gold besar box',
            'Permata gold kecil box',
            'Gliter gel',
            'Mutiara set',
            'Manik aurora box',
            'Glitter ungu',
            'Acc kupu',
            'Bunga putih campur box',
            'Caviar gold',
            'Permata silver',
            'Permata aurora',
            'Gliter gold',
            'Misscheering builder',
            'Akrilik bubuk putih',
            '3D clear',
            'Builder clear',
            'Glitter rose gold',
            'Spider gel',
            'Lem AS',
            'Monumer akrilik',
            'Hand light',
            'Footfile',
            'Spons ombre',
            'Micelar',
            'Plastik wrap',
            'Bath salt',
            'Milk bath cuccio',
            'Lotion menail',
            'Aceton biru',
            'Lotion cuccio',
            'Remover peony',
            'Microbrush',
            'Primer bonder blueyes',
            'Cleanser iconsight',
            'Tint iconsight hitam',
            'Tint iconsight coffe',
            'Primer',
            'Bonder',
            'Facepaint putih',
            'Lash remover navina',
            'Sisir eyelash',
            'Brush lip',
            'Dancing swan',
            'Manga lash',
            'Spike wet lash',
            'Wax stripe bungkus',
            'Wax stripe menail 100',
            'Prewax cleanser',
            'Oil waxing',
            'Repairing cream wax',
            'Cooldown wax',
            'Baby oil',
            'Stik besar',
            'Lash glue iconsight',
            'Step 1',
            'Steap 2',
            'Vitamin',
            'Sisir lash lift',
            'Lash lift patch',
            'movaya soft gel S',
            'aceton pink',
            'movaya xs',
            'drill baru',
            'UV baru',
            'kuku latian',
            'kuku kaki',
            'born pretty bg125',
            'born pretty bg090',
            'rising lady mikywhite',
            'rising lady',
            'rising lady cat eye biru',
            'rising lady primer',
            'Kupal S rising lady',
            'Builder misscheering',
            'Buffer kasar',
            'Buffer Halus',
            'Brush manicure',
            'Foot brush',
            'Gunting Kuku Besar',
            'Pusher',
            'Dooting tools',
            'Kuas Emas',
            'Kuas liner',
            'Vitamin biola',
            'Mutiara set',
            'Foil set',
            'Kupal XS',
            'Kupal S',
            'Nail file besar',
            'Toe separator',
            'Spons ombre',
            'Lidah ular',
            'Stik akrilik',
            'Top coat press on(MSY)',
            'Gel 3D clear',
            'remover charzieg',
            'Gunting kuku kecil',
            'pinset aksesoris',
            'Pinset bulu',
            'Foof file mini',
            'Foot file besar',
            'Jepit kuku remover set',
            'Lem kupal byb',
            'Lem mxbon pink',
            'Peony kutek 42',
            'Peony cat eye 44',
            'Cat eye 009',
            'Big gliter',
            'Liner hitam',
            'Top coat roniki',
            'Base coat roniki',
            'Top shimmer',
            'Cuticle oil AS',
            'Cuticle oil biola',
            'Cuticle BNC',
            'Eye patch',
            'Cleansing foam iconsign',
            'Lash lift step 1 peony',
            'Lash lift step 2 peony',
            'Coating eyelash blue eyes',
            'Remover eyelash',
            'Ph bond ouboli',
            'Stik kayu press on',
            'Dappen glass',
            'Cairan softlens',
            'Collagen tangan',
            'Collagen kaki',
            'Eye tape',
            'Refil foot amplas',
            'Biji wax',
            'Kuas nail',
            'Body scrub kopi',
            'Body scrub bengkoang',
            'Masker isi 50',
            'Strip wa menail isi 50',
            'aceton pink',
            'Kasa',
            'Micelar',
            'lem lady black',
            'movaya soft gel premium',
            'yelix flora lshes 5D',
            'peonynail softener',
            'sisir eyelash',
            'matte top peony',
            'blooming gel peony',
            'peonycolor25',
            'peony color 44',
            'ouboli top coat',
            'micro brush pink',
            'yelix ukuran 10mm D fanning',
            'movaya soft gel almond s',
            'movaya soft gel xs',
            'rising lady base coat',
            'rising lady primer',
            'born pretty milky jelly gel',
            'rising ladybase coat halal',
            'trash bag/kantong sampah',
            'Kupal xS rising lady',
        ];

        // 4. Clean and Deduplicate
        $products = array_unique(array_map('trim', $rawProducts));

        foreach ($products as $productName) {
            Product::create([
                'category_id' => $category->id,
                'unit_id' => $unit->id,
                'name' => $productName,
                'price' => 0,
            ]);
        }
    }
}
